# This file is covered by the LICENSE file in the root of this project.
# Status of Salzburg Bicycle LiDAR Dataset: 28.11.2022 - more labels may follow in future iterations of the dataset.
# Armin Niedermueller - www.github.com/nerovalerius
labels: 
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"
color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  256: [255, 0, 0]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points
 0: 0.2924378538693584
 1: 0.00033992705070193756
 10: 0.0009364391170669451
 11: 0.0
 13: 0.0
 15: 6.012153382062884e-06
 16: 0.0
 18: 2.115964729086901e-06
 20: 0.0
 30: 2.7701879568395407e-05
 31: 0.00022343876899872376
 32: 0.0
 40: 0.11421055009281819
 44: 0.000357655325443787
 48: 0.00028486918436013457
 49: 1.2254901960784314e-07
 50: 0.020413291130061493
 51: 0.04282368749274858
 52: 0.010208578431372548
 60: 0.0
 70: 0.2744678225432185
 71: 0.0
 72: 0.2407751457535677
 80: 0.0010160430444367096
 81: 0.0005287888676180531
 99: 0.00022525597517113354
 252: 0.0001818192365703678
 253: 0.0002955120953706927
 254: 0.00020443714468035734
 255: 0.0
 256: 0.0
 257: 0.0
 258: 1.2012704490080055e-05
 259: 2.0919625246548323e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0     # "unlabeled"
  1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 2     # "bicycle"
  13: 5     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 3     # "motorcycle"
  16: 5     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 4     # "truck"
  20: 5     # "other-vehicle"
  30: 6     # "person"
  31: 7     # "bicyclist"
  32: 8     # "motorcyclist"
  40: 9     # "road"
  44: 10    # "parking"
  48: 11    # "sidewalk"
  49: 12    # "other-ground"
  50: 13    # "building"
  51: 14    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 9     # "lane-marking" to "road" ---------------------------------mapped
  70: 15    # "vegetation"
  71: 16    # "trunk"
  72: 17    # "terrain"
  80: 18    # "pole"
  81: 19    # "traffic-sign"
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 7    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 6    # "moving-person" to "person" ------------------------------mapped
  255: 8    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 5    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 5    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 4    # "moving-truck" to "truck" --------------------------------mapped
  259: 5    # "moving-other"-vehicle to "other-vehicle" ----------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10     # "car"
  2: 11     # "bicycle"
  3: 15     # "motorcycle"
  4: 18     # "truck"
  5: 20     # "other-vehicle"
  6: 30     # "person"
  7: 31     # "bicyclist"
  8: 32     # "motorcyclist"
  9: 40     # "road"
  10: 44    # "parking"
  11: 48    # "sidewalk"
  12: 49    # "other-ground"
  13: 50    # "building"
  14: 51    # "fence"
  15: 70    # "vegetation"
  16: 71    # "trunk"
  17: 72    # "terrain"
  18: 80    # "pole"
  19: 81    # "traffic-sign"
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: True      # "car"
  2: True     # "bicycle"
  3: True     # "motorcycle"
  4: True     # "truck"
  5: True     # "other-vehicle"
  6: True     # "person"
  7: True     # "bicyclist"
  8: True     # "motorcyclist"
  9: False     # "road"
  10: True    # "parking"
  11: True    # "sidewalk"
  12: True    # "other-ground"
  13: False    # "building"
  14: True    # "fence"
  15: False    # "vegetation"
  16: True    # "trunk"
  17: False    # "terrain"
  18: True    # "pole"
  19: True    # "traffic-sign"
split: # sequence numbers
  train:
    - 2
    - 3  
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
    - 11 
    - 14
    - 16
    - 18
    - 23
    - 24
    - 25
    - 27
    - 28
  valid:
    - 2
    - 3  
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
    - 11 
    - 14
    - 16
    - 18
    - 23
    - 24
    - 25
    - 27
    - 28
  test:
    - 2
    - 3  
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
    - 11 
    - 14
    - 16
    - 18
    - 23
    - 24
    - 25
    - 27
    - 28
