# Config format schema number
format_version: 4

# Status of Salzburg Bicycle LiDAR Dataset: 28.11.2022 - more labels may follow in future iterations of the dataset.
# Armin Niedermueller - www.github.com/nerovalerius

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 20
  num_input_features: 16
  use_norm: True
  init_size: 32


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SBLD"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/sbld.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  #data_path: "../datasets_mta/sbld_short_for_testing/sequences"
  data_path: "../datasets_mta/sbld_train_val_test/train/sequences"
  imageset: "train"
  return_ref: True
  batch_size: 1
  shuffle: True
  num_workers: 4

val_data_loader:
  #data_path: "../datasets_mta/sbld_short_for_testing/sequences"
  data_path: "../datasets_mta/sbld_train_val_test/val/sequences"
  imageset: "val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 4


###################
## Train params
train_params:
  #model_load_path: ""
  model_load_path: "trained_models/load/attncyl3dv3_20_epochs_kitti_14_epochs_sbld_best_val_miou.pt"
  model_save_path: "trained_models/save/model.pt"
  model_save_path_early_stop: "trained_models/save/model_early_stop.pt"
  model_save_path_best_val_miou: "trained_models/save/model_best_val_miou.pt"
  checkpoint_every_n_steps: 2000
  max_num_epochs: 20
  eval_every_n_steps: 2000
  learning_rate: 0.001